name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "rm -rf ~/my-bot && mkdir ~/my-bot"
          scp -r . ${{ secrets.EC2_HOST }}:~/my-bot

      - name: Upload .env to EC2
        run: |
          echo "${{ secrets.ENV_FILE }}" | ssh ${{ secrets.EC2_HOST }} "cat > ~/my-bot/.env"

      - name: Build and run Docker container on EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-bot
            sudo docker build -t twitch-bot .
            sudo docker stop twitch-bot || true
            sudo docker rm twitch-bot || true
            sudo docker run -d --name twitch-bot --env-file .env -p 3000:3000 twitch-bot
          EOF
