name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "rm -rf ~/app && mkdir ~/app"
          scp -r . ${{ secrets.EC2_HOST }}:~/app

      - name: Build and run on EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app
            docker build -t my-app .
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 3000:3000 my-app
          EOF
